In [1]:
library(ggplot2)
library(data.table)
library(stringr)
theme_set(theme_bw())

In [2]:
tools = c('singlem', 'sylph')
d1 = data.table(tool = tools, sample = "SRR8648366")

In [3]:
readit = function(tool, sample){
    to_read = paste0('output_',tool,'/', tool, '/',sample,'.profile')
    return(fread(to_read))
}
d2 = d1[, readit(tool, sample)[, c("coverage", "taxonomy")], by=list(tool, sample)]
d2[, relabu := coverage / sum(coverage, na.rm = TRUE), by = list(tool, sample)]
d2[, taxonomy := gsub("; ", ";", gsub("Root; ", "", taxonomy))]

In [4]:
m = dcast(d2, sample + taxonomy ~ tool, value.var = c("relabu", "coverage"), fill = 0)
setnames(m, names(m), gsub("_", "__", names(m)))

In [17]:
format_table <- function(m) {
    cov_cols <- grep("^coverage_|_coverage$", names(m), value = TRUE)
    mtmp = m[,which(!grepl("^relabu_|_relabu$", names(m))), with = FALSE]
    mtmp[
        ,
        c(cov_cols, "taxonomy") := c(
            .SD[, cov_cols, with = FALSE],
            list(purrr::map(strsplit(taxonomy, "; ?"), function(x) paste0(tail(x,2), collapse = "; ")))
        )
    ][]
}

In [20]:
# kingdom
format_table(
    m[grep("d__", taxonomy),
      lapply(.SD, sum),
      by = list(sample, taxonomy = gsub(";p__.*", "", taxonomy))]
)

  sample     taxonomy    coverage__singlem coverage__sylph
1 SRR8648366 d__Archaea    24.02             4.513
2 SRR8648366 d__Bacteria 3949.20           422.244

In [23]:
# phylum
format_table(
    m[!grepl("d__Archaea", taxonomy) & grepl(";p__", taxonomy),
      lapply(.SD, sum),
      by = list(sample, taxonomy = gsub(";c__.*", "", taxonomy))][coverage__sylph > 1]
)

  sample     taxonomy                         coverage__singlem coverage__sylph
1 SRR8648366 d__Bacteria; p__Actinobacteriota 2412.07           252.468
2 SRR8648366 d__Bacteria; p__Bacteroidota      361.75            38.146
3 SRR8648366 d__Bacteria; p__Firmicutes         82.91            33.306
4 SRR8648366 d__Bacteria; p__Firmicutes_A      123.84            44.409
5 SRR8648366 d__Bacteria; p__Myxococcota        10.13             1.609
6 SRR8648366 d__Bacteria; p__Proteobacteria    581.00            44.555
7 SRR8648366 d__Bacteria; p__Spirochaetota       3.81             2.314

In [25]:
# class
format_table(
    m[!grepl("d__Archaea", taxonomy) & grepl(";c__", taxonomy),
      lapply(.SD, sum),
      by = list(sample, taxonomy = gsub(";o__.*", "", taxonomy))][coverage__sylph > 1]
)

  sample     taxonomy                                  coverage__singlem
1 SRR8648366 p__Actinobacteriota; c__Actinomycetia     2269.85
2 SRR8648366 p__Bacteroidota; c__Bacteroidia            341.48
3 SRR8648366 p__Firmicutes; c__Bacilli                   82.91
4 SRR8648366 p__Firmicutes_A; c__Clostridia             123.39
5 SRR8648366 p__Myxococcota; c__Polyangia                 2.75
6 SRR8648366 p__Proteobacteria; c__Alphaproteobacteria   50.79
7 SRR8648366 p__Proteobacteria; c__Gammaproteobacteria  530.21
8 SRR8648366 p__Spirochaetota; c__Spirochaetia            3.75
  coverage__sylph
1 251.125
2  38.146
3  33.306
4  44.409
5   1.384
6   3.940
7  40.615
8   2.314

In [26]:
# order
format_table(
    m[!grepl("d__Archaea", taxonomy) & grepl(";o__", taxonomy),
      lapply(.SD, sum),
      by = list(sample, taxonomy = gsub(";f__.*", "", taxonomy))][coverage__sylph > 1]
)

   sample     taxonomy                                    coverage__singlem
1  SRR8648366 c__Actinomycetia; o__Actinomycetales        1411.27
2  SRR8648366 c__Actinomycetia; o__Mycobacteriales         521.11
3  SRR8648366 c__Actinomycetia; o__Propionibacteriales     241.89
4  SRR8648366 c__Actinomycetia; o__Streptosporangiales      19.90
5  SRR8648366 c__Bacteroidia; o__Bacteroidales              59.50
6  SRR8648366 c__Bacteroidia; o__Flavobacteriales          164.17
7  SRR8648366 c__Bacilli; o__Acholeplasmatales               9.79
8  SRR8648366 c__Bacilli; o__Bacillales_D                   11.21
9  SRR8648366 c__Bacilli; o__Erysipelotrichales              4.45
10 SRR8648366 c__Bacilli; o__Haloplasmatales_A               3.34
11 SRR8648366 c__Bacilli; o__Lactobacillales                25.56
12 SRR8648366 c__Bacilli; o__RF39                            6.34
13 SRR8648366 c__Bacilli; o__Staphylococcales                5.88
14 SRR8648366 c__Clostridia; o__Christensenellales          11.62
15 SRR8648366 c__Clostridia; o__Clostridiales               23.40
16 SRR8648366 c__Clostridia; o__Lachnospirales              11.57
17 SRR8648366 c__Clostridia; o__Oscillospirales             23.95
18 SRR8648366 c__Clostridia; o__Peptostreptococcales        25.77
19 SRR8648366 c__Clostridia; o__Saccharofermentanales       12.35
20 SRR8648366 c__Clostridia; o__Tissierellales               9.04
21 SRR8648366 c__Polyangia; o__Polyangiales                  2.34
22 SRR8648366 c__Alphaproteobacteria; o__Rhizobiales        12.65
23 SRR8648366 c__Alphaproteobacteria; o__Rhodobacterales    19.90
24 SRR8648366 c__Gammaproteobacteria; o__Burkholderiales    25.75
25 SRR8648366 c__Gammaproteobacteria; o__Enterobacterales   11.81
26 SRR8648366 c__Gammaproteobacteria; o__Pseudomonadales    85.69
27 SRR8648366 c__Gammaproteobacteria; o__Xanthomonadales   345.51
28 SRR8648366 c__Spirochaetia; o__Treponematales             2.10
   coverage__sylph
1  171.775
2   73.607
3    4.377
4    1.215
5   30.037
6    8.109
7    1.434
8    1.829
9    1.519
10   2.130
11  17.688
12   1.432
13   5.409
14   5.789
15   9.675
16   3.595
17   8.824
18   6.964
19   7.387
20   1.180
21   1.384
22   1.773
23   1.415
24   5.804
25   4.134
26  17.006
27  13.460
28   1.891

In [27]:
# family
format_table(
    m[!grepl("d__Archaea", taxonomy) & grepl(";f__", taxonomy),
      lapply(.SD, sum),
      by = list(sample, taxonomy = gsub(";g__.*", "", taxonomy))][coverage__sylph > 1]
)

   sample     taxonomy
1  SRR8648366 o__Actinomycetales; f__Beutenbergiaceae
2  SRR8648366 o__Actinomycetales; f__Brevibacteriaceae
3  SRR8648366 o__Actinomycetales; f__Cellulomonadaceae
4  SRR8648366 o__Actinomycetales; f__Dermabacteraceae
5  SRR8648366 o__Actinomycetales; f__Dermatophilaceae
6  SRR8648366 o__Actinomycetales; f__Microbacteriaceae
7  SRR8648366 o__Mycobacteriales; f__Mycobacteriaceae
8  SRR8648366 o__Mycobacteriales; f__Pseudonocardiaceae
9  SRR8648366 o__Propionibacteriales; f__Propionibacteriaceae
10 SRR8648366 o__Streptosporangiales; f__Streptosporangiaceae
11 SRR8648366 o__Bacteroidales; f__Bacteroidaceae
12 SRR8648366 o__Bacteroidales; f__Dysgonomonadaceae
13 SRR8648366 o__Bacteroidales; f__Marinilabiliaceae
14 SRR8648366 o__Bacteroidales; f__Muribaculaceae
15 SRR8648366 o__Bacteroidales; f__Paludibacteraceae
16 SRR8648366 o__Bacteroidales; f__UBA3663
17 SRR8648366 o__Bacteroidales; f__UBA932
18 SRR8648366 o__Flavobacteriales; f__Flavobacteriaceae
19 SRR8648366 o__Acholeplasmatales; f__Acholeplasmataceae
20 SRR8648366 o__Bacillales_D; f__Amphibacillaceae
21 SRR8648366 o__Erysipelotrichales; f__Erysipelotrichaceae
22 SRR8648366 o__Haloplasmatales_A; f__Turicibacteraceae
23 SRR8648366 o__Lactobacillales; f__Aerococcaceae
24 SRR8648366 o__Lactobacillales; f__Lactobacillaceae
25 SRR8648366 o__Lactobacillales; f__Streptococcaceae
26 SRR8648366 o__RF39; f__UBA660
27 SRR8648366 o__Staphylococcales; f__Salinicoccaceae
28 SRR8648366 o__Staphylococcales; f__Staphylococcaceae
29 SRR8648366 o__Christensenellales; f__CAG-138
30 SRR8648366 o__Christensenellales; f__CAG-74
31 SRR8648366 o__Clostridiales; f__Clostridiaceae
32 SRR8648366 o__Lachnospirales; f__Lachnospiraceae
33 SRR8648366 o__Oscillospirales; f__Acutalibacteraceae
34 SRR8648366 o__Oscillospirales; f__Oscillospiraceae
35 SRR8648366 o__Oscillospirales; f__Ruminococcaceae
36 SRR8648366 o__Peptostreptococcales; f__Acidaminobacteraceae
37 SRR8648366 o__Saccharofermentanales; f__DTU023
38 SRR8648366 o__Tissierellales; f__Peptoniphilaceae
39 SRR8648366 o__Polyangiales; f__Polyangiaceae
40 SRR8648366 o__Rhizobiales; f__Devosiaceae
41 SRR8648366 o__Rhodobacterales; f__Rhodobacteraceae
42 SRR8648366 o__Burkholderiales; f__Burkholderiaceae
43 SRR8648366 o__Enterobacterales; f__Alteromonadaceae
44 SRR8648366 o__Enterobacterales; f__Enterobacteriaceae
45 SRR8648366 o__Pseudomonadales; f__Halomonadaceae
46 SRR8648366 o__Pseudomonadales; f__Oleiphilaceae
47 SRR8648366 o__Pseudomonadales; f__Pseudomonadaceae
48 SRR8648366 o__Xanthomonadales; f__Xanthomonadaceae
49 SRR8648366 o__Treponematales; f__Treponemataceae
   coverage__singlem coverage__sylph
1   88.61              2.483
2   46.74             20.681
3   34.79              1.086
4   74.48              3.965
5  979.46            140.619
6   82.61              1.357
7  310.89             69.718
8   54.79              3.696
9   92.21              4.377
10  19.90              1.215
11  10.59              6.966
12  19.57             11.212
13   4.26              3.822
14   0.69              1.006
15   3.60              1.249
16   1.66              1.452
17   6.97              3.325
18 100.40              6.974
19   2.92              1.162
20  10.69              1.829
21   4.39              1.519
22   3.34              2.130
23   2.15              1.224
24   8.69              5.911
25  12.34             10.553
26   6.34              1.432
27   1.81              1.560
28   3.62              3.849
29   2.91              2.853
30   6.05              2.234
31  23.40              9.675
32  11.23              3.595
33   3.61              1.170
34  13.68              4.818
35   3.15              1.461
36   8.98              5.742
37  10.76              7.039
38   5.34              1.029
39   1.15              1.286
40   2.73              1.140
41  19.90              1.415
42  20.61              5.427
43   3.32              2.036
44   2.28              1.562
45  20.96              2.654
46  19.59              6.392
47  12.62              6.782
48  88.08             13.460
49   2.10              1.891

In [28]:
# How well does genus level rescue some of the missing genomes? First need to remake the table with genus level, annoying since kraken profiles are filled, when the rest aren't.
format_table(
    m[!grepl("d__Archaea", taxonomy) & grepl(";g__", taxonomy),
      lapply(.SD, sum),
      by = list(sample, taxonomy = gsub(";s__.*", "", taxonomy))][coverage__sylph > 1]
)

   sample     taxonomy                                    coverage__singlem
1  SRR8648366 f__Beutenbergiaceae; g__Ruania               74.01
2  SRR8648366 f__Brevibacteriaceae; g__Brevibacterium      37.09
3  SRR8648366 f__Dermabacteraceae; g__Brachybacterium      73.72
4  SRR8648366 f__Dermatophilaceae; g__F2B08               103.62
5  SRR8648366 f__Dermatophilaceae; g__Janibacter          132.76
6  SRR8648366 f__Dermatophilaceae; g__Ornithinimicrobium  184.53
7  SRR8648366 f__Microbacteriaceae; g__Gulosibacter         2.31
8  SRR8648366 f__Mycobacteriaceae; g__Corynebacterium      74.19
9  SRR8648366 f__Mycobacteriaceae; g__Dietzia              23.00
10 SRR8648366 f__Mycobacteriaceae; g__Mycobacterium        84.31
11 SRR8648366 f__Mycobacteriaceae; g__Rhodococcus           8.61
12 SRR8648366 f__Pseudonocardiaceae; g__Saccharomonospora   6.53
13 SRR8648366 f__Propionibacteriaceae; g__Arachnia         19.70
14 SRR8648366 f__Propionibacteriaceae; g__Enemella          7.26
15 SRR8648366 f__Propionibacteriaceae; g__JAAYAO01          3.61
16 SRR8648366 f__Bacteroidaceae; g__Prevotella              7.70
17 SRR8648366 f__Dysgonomonadaceae; g__Fermentimonas        5.32
18 SRR8648366 f__Dysgonomonadaceae; g__Proteiniphilum      11.47
19 SRR8648366 f__Dysgonomonadaceae; g__UBA2632              1.88
20 SRR8648366 f__Marinilabiliaceae; g__Geofilum             4.26
21 SRR8648366 f__UBA3663; g__UBA3663                        1.66
22 SRR8648366 f__UBA932; g__Cryptobacteroides               5.82
23 SRR8648366 f__Flavobacteriaceae; g__Aequorivita         25.77
24 SRR8648366 f__Acholeplasmataceae; g__DUQW01              1.59
25 SRR8648366 f__Amphibacillaceae; g__Ornithinibacillus     2.18
26 SRR8648366 f__Turicibacteraceae; g__Turicibacter         3.34
27 SRR8648366 f__Lactobacillaceae; g__Lactobacillus         3.84
28 SRR8648366 f__Lactobacillaceae; g__Limosilactobacillus   4.01
29 SRR8648366 f__Streptococcaceae; g__Streptococcus        12.34
30 SRR8648366 f__Staphylococcaceae; g__Mammaliicoccus       1.58
31 SRR8648366 f__Staphylococcaceae; g__Staphylococcus       1.70
32 SRR8648366 f__CAG-138; g__PeH17                          1.10
33 SRR8648366 f__CAG-74; g__DTU024                          2.14
34 SRR8648366 f__Clostridiaceae; g__Clostridium            22.41
35 SRR8648366 f__Oscillospiraceae; g__CAG-83                0.99
36 SRR8648366 f__Oscillospiraceae; g__Faecousia             5.33
37 SRR8648366 f__Acidaminobacteraceae; g__DUPT01            6.71
38 SRR8648366 f__DTU023; g__DTU032                          3.68
39 SRR8648366 f__DTU023; g__DUPJ01                          6.33
40 SRR8648366 f__Polyangiaceae; g__NIC37A-2                 0.75
41 SRR8648366 f__Devosiaceae; g__Pelagibacterium            1.98
42 SRR8648366 f__Burkholderiaceae; g__Oligella              5.21
43 SRR8648366 f__Alteromonadaceae; g__Aliidiomarina         1.81
44 SRR8648366 f__Enterobacteriaceae; g__Escherichia         0.81
45 SRR8648366 f__Halomonadaceae; g__Halomonas              16.23
46 SRR8648366 f__Oleiphilaceae; g__Marinobacter            18.85
47 SRR8648366 f__Pseudomonadaceae; g__Pseudomonas_D         3.25
48 SRR8648366 f__Pseudomonadaceae; g__Thiopseudomonas       7.30
49 SRR8648366 f__Xanthomonadaceae; g__Luteimonas           20.97
50 SRR8648366 f__Xanthomonadaceae; g__Lysobacter            9.49
51 SRR8648366 f__Treponemataceae; g__Treponema_D            1.99
   coverage__sylph
1   2.136
2  20.681
3   3.965
4  57.276
5   2.683
6  80.175
7   1.037
8  54.504
9   4.428
10  9.084
11  1.702
12  3.062
13  1.560
14  1.242
15  1.575
16  4.979
17  3.801
18  6.185
19  1.226
20  3.822
21  1.452
22  2.776
23  6.748
24  1.162
25  1.219
26  2.130
27  2.599
28  2.884
29 10.553
30  1.722
31  2.127
32  1.327
33  1.235
34  9.596
35  1.027
36  1.199
37  4.801
38  2.830
39  3.955
40  1.286
41  1.140
42  4.827
43  1.571
44  1.075
45  2.654
46  6.392
47  2.583
48  4.199
49 11.909
50  1.551
51  1.710

In [33]:
# Species level
format_table(m[!grepl("d__Archaea", taxonomy) & grepl(";s__", taxonomy)][coverage__sylph > 1])

   sample     taxonomy
1  SRR8648366 g__Ruania; s__Ruania albidiflava
2  SRR8648366 g__Brevibacterium; s__Brevibacterium epidermidis
3  SRR8648366 g__Brevibacterium; s__Brevibacterium intestinavium
4  SRR8648366 g__Brachybacterium; s__Brachybacterium massiliense
5  SRR8648366 g__Brachybacterium; s__Brachybacterium paraconglomeratum
6  SRR8648366 g__F2B08; s__F2B08 sp012729695
7  SRR8648366 g__F2B08; s__F2B08 sp012838445
8  SRR8648366 g__Janibacter; s__Janibacter corallicola
9  SRR8648366 g__Ornithinimicrobium; s__Ornithinimicrobium sp003577095
10 SRR8648366 g__Gulosibacter; s__Gulosibacter sp012719255
11 SRR8648366 g__Corynebacterium; s__Corynebacterium casei
12 SRR8648366 g__Corynebacterium; s__Corynebacterium humireducens
13 SRR8648366 g__Corynebacterium; s__Corynebacterium pollutisoli
14 SRR8648366 g__Corynebacterium; s__Corynebacterium sp012838715
15 SRR8648366 g__Corynebacterium; s__Corynebacterium sp012838985
16 SRR8648366 g__Corynebacterium; s__Corynebacterium stationis
17 SRR8648366 g__Dietzia; s__Dietzia sp012841845
18 SRR8648366 g__Mycobacterium; s__Mycobacterium koreense
19 SRR8648366 g__Rhodococcus; s__Rhodococcus sp012729135
20 SRR8648366 g__Saccharomonospora; s__Saccharomonospora viridis
21 SRR8648366 g__Arachnia; s__Arachnia sp012837465
22 SRR8648366 g__Enemella; s__Enemella sp012839035
23 SRR8648366 g__JAAYAO01; s__JAAYAO01 sp012719335
24 SRR8648366 g__Fermentimonas; s__Fermentimonas sp012513315
25 SRR8648366 g__Fermentimonas; s__Fermentimonas sp012841425
26 SRR8648366 g__Proteiniphilum; s__Proteiniphilum sp012799155
27 SRR8648366 g__Proteiniphilum; s__Proteiniphilum sp016916535
28 SRR8648366 g__UBA2632; s__UBA2632 sp012840785
29 SRR8648366 g__Geofilum; s__Geofilum rhodophaeum
30 SRR8648366 g__Geofilum; s__Geofilum sp012838865
31 SRR8648366 g__UBA3663; s__UBA3663 sp004557315
32 SRR8648366 g__Aequorivita; s__Aequorivita sinensis
33 SRR8648366 g__DUQW01; s__DUQW01 sp012520715
34 SRR8648366 g__Turicibacter; s__Turicibacter sp001543345
35 SRR8648366 g__Lactobacillus; s__Lactobacillus johnsonii
36 SRR8648366 g__Limosilactobacillus; s__Limosilactobacillus reuteri
37 SRR8648366 g__Streptococcus; s__Streptococcus alactolyticus
38 SRR8648366 g__Mammaliicoccus; s__Mammaliicoccus sciuri
39 SRR8648366 g__Staphylococcus; s__Staphylococcus arlettae
40 SRR8648366 g__DTU024; s__DTU024 sp012837525
41 SRR8648366 g__Clostridium; s__Clostridium sp000435835
42 SRR8648366 g__Clostridium; s__Clostridium sp900543325
43 SRR8648366 g__DUPT01; s__DUPT01 sp012799095
44 SRR8648366 g__DUPT01; s__DUPT01 sp012838225
45 SRR8648366 g__DTU032; s__DTU032 sp002427475
46 SRR8648366 g__DUPJ01; s__DUPJ01 sp012837885
47 SRR8648366 g__NIC37A-2; s__NIC37A-2 sp012514535
48 SRR8648366 g__Pelagibacterium; s__Pelagibacterium sp003390885
49 SRR8648366 g__Oligella; s__Oligella sp012511095
50 SRR8648366 g__Aliidiomarina; s__Aliidiomarina taiwanensis
51 SRR8648366 g__Escherichia; s__Escherichia coli
52 SRR8648366 g__Halomonas; s__Halomonas alimentaria
53 SRR8648366 g__Halomonas; s__Halomonas stercoripullorum
54 SRR8648366 g__Marinobacter; s__Marinobacter vinifirmus
55 SRR8648366 g__Pseudomonas_D; s__Pseudomonas_D formosensis
56 SRR8648366 g__Pseudomonas_D; s__Pseudomonas_D sp012735335
57 SRR8648366 g__Thiopseudomonas; s__Thiopseudomonas sp012728415
58 SRR8648366 g__Luteimonas; s__Luteimonas sp001717465
59 SRR8648366 g__Luteimonas; s__Luteimonas sp012515985
60 SRR8648366 g__Lysobacter; s__Lysobacter defluvii
   coverage__singlem coverage__sylph
1  23.60              2.136
2   0.00              1.355
3  27.17             18.178
4  10.18              2.379
5   5.26              1.586
6   7.12              4.798
7  79.93             52.478
8  55.36              2.683
9  56.63             80.175
10  1.42              1.037
11  6.43              5.167
12 24.54             13.704
13  8.79              6.519
14  3.19              4.504
15 14.93             21.866
16  2.17              1.481
17  5.74              4.428
18 19.51              7.582
19  4.03              1.702
20  2.02              1.338
21  5.25              1.560
22  1.80              1.242
23  2.34              1.575
24  0.00              1.032
25  1.56              1.474
26  0.80              1.710
27  7.82              4.475
28  1.38              1.226
29  0.50              1.124
30  3.38              2.698
31  0.75              1.029
32  8.99              6.088
33  1.40              1.162
34  3.34              2.130
35  1.31              1.816
36  1.52              2.884
37 12.34             10.294
38  1.29              1.722
39  1.53              1.691
40  0.78              1.003
41  3.14              8.328
42  0.00              1.087
43  4.33              3.312
44  1.65              1.489
45  2.92              2.582
46  5.78              3.501
47  0.70              1.286
48  1.61              1.140
49  4.88              4.827
50  1.71              1.571
51  0.00              1.075
52  2.78              1.169
53  0.00              1.485
54  8.56              5.808
55  1.56              1.204
56  0.69              1.379
57  5.49              4.199
58 10.01              6.476
59  1.90              5.433
60  3.20              1.551